name: UUIDBan
author: WolfLeader116
main: io.github.wolfleader116.uuidban.UUIDBan
version: 1.0
description: An UUID Ban Plugin for Minecraft 1.6
commands:
  uuidban:
    description: Ban a player via UUID
  uuidunban:
    description: Unban a player via UUID
permissions:
  uuidban.ban:
    description: Allows the player to uuid ban players
  uuidban.unban:
    description: Allows the player to uuid unban players
  uuidban.*:
    description: Allows the player complete access to all UUIDBan permissions
    children:
      uuidban.ban: true
      uuidban.unban: true
